# Liste des id constants dans la BDD

# LETTRE DES IDENTIFIANT POUR L'ENT DU RHONE
LETTRE_PROJET_LACLASSE = "V"
CHIFFR_PROJET_LACLASSE = "6"

#
# TypeTelephone
# 
TYP_TEL_MAIS = "MAISON"
TYP_TEL_PORT = "PORTABLE"
TYP_TEL_TRAV = "TRAVAIL"
TYP_TEL_AUTR = "AUTRE"

#
# TypeRelationEleve
#
TYP_REL_PAR = "PAR"
TYP_REL_NPAR = "NPAR"
TYP_REL_RLGL = "RLGL"
TYP_REL_FINA = "FINA"
TYP_REL_CORR = "CORR"

#
# TypeRegroupement
#
TYP_REG_CLS = "CLASSE"
TYP_REG_GRP = "GROUPE"
TYP_REG_LBR = "LIBRE"

#
# TypeEtablissement
#
TYP_ETB_CTR_PU = "PU"

#
# Service
#
SRV_LACLASSE = "LACLASSE"
SRV_ETAB = "ETAB"
# Le nom des service de regroupement est le même que les types de regroupement
SRV_CLASSE = TYP_REG_CLS
SRV_GROUPE = TYP_REG_GRP
SRV_LIBRE = TYP_REG_LBR
SRV_USER = "USER"
SRV_SERVICE = "SERVICE"

#
# Profil
#
PRF_ELV = "ELV"
PRF_ENS = "ENS"
PRF_DIR = "DIR"
PRF_PAR = "PAR"
PRF_ADM = "ADM"

#
# Role
#
ROL_TECH = "TECH"
ROL_ELV_ETB = "ELV_ETB"
ROL_PROF_ETB = "PROF_ETB"
ROL_ADM_ETB = "ADM_ETB"
ROL_PAR_ETB = "PAR_ETB"
ROL_DIR_ETB = "DIR_ETB"
ROL_CPE_ETB = "CPE_ETB"
ROL_BUR_ETB = "BUR_ETB"

ROL_PROF_CLS = "PROF_CLS"
ROL_ELV_CLS = "ELV_CLS"
ROL_PRFP_CLS = "PRFP_CLS"

#
# Activite
#
ACT_CREATE_USER = "CREATE_USER"
ACT_DELETE_USER = "DELETE_USER"
ACT_UPDATE_USER = "UPDATE_USER"
ACT_READ_USER = "READ_USER"
ACT_CREATE = "CREATE"

#
# TypeParam
#
TYP_PARAM_BOOL = "BOOLEAN"
TYP_PARAM_TEXT = "TEXT"
TYP_PARAM_NUMBER = "NUMBER"