# Liste des id constants dans la BDD

#
# TypeTelephone
# 
TYP_TEL_MAIS = "MAIS"
TYP_TEL_PORT = "PORT"
TYP_TEL_TRAV = "TRAV"
TYP_TEL_AUTR = "AUTR"

#
# TypeRelationEleve
#
TYP_REL_PAR = "PAR"
TYP_REL_NPAR = "NPAR"
TYP_REL_RLGL = "RLGL"
TYP_REL_FINA = "FINA"
TYP_REL_CORR = "CORR"

#
# TypeRegroupement
#
TYP_REG_CLS = "CLS"
TYP_REG_GRP = "GRP"
TYP_REG_LBR = "LBR"

#
# Service
#
SRV_LACLASSE = "LACLASSE"
SRV_ETAB = "ETAB"
SRV_CLASSE = "CLASSE"
SRV_GROUPE = "GROUPE"
SRV_LIBRE = "LIBRE"
SRV_USER = "USER"

#
# Role
#
ROL_TECH = "TECH"
ROL_ELV_ETB = "ELV_ETB"
ROL_PROF_ETB = "PROF_ETB"
ROL_ADM_ETB = "ADM_ETB"
ROL_PAR_ETB = "PAR_ETB"
ROL_DIR_ETB = "DIR_ETB"
ROL_CPE_ETB = "CPE_ETB"
ROL_BUR_ETB = "BUR_ETB"

ROL_PROF_CLS = "PROF_CLS"
ROL_ELV_CLS = "ELV_CLS"
ROL_PRFP_CLS = "PRFP_CLS"